# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif
# https://github.com/JeanRibes/nilfs2-mounter
%global goipath         github.com/JeanRibes/nilfs2-mounter
%global commit          %(git rev-parse HEAD)

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Mount NILFS2 snapshots without sudo.}

%global godocs          README.md

Name:           nilfs2-mounter
Version:        %(git describe --tags --exact-match --dirty|grep -v dirty|grep v||git rev-parse HEAD)
Release:        %(git rev-parse --short HEAD)
Summary:        Mount NILFS2 snapshots without sudo

License:        # FIXME
URL:            %{gourl}
Source:         %{name}-%{commit}.tar.gz
# %{gosource}

Requires:	nilfs-utils
Requires:	bash

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/nilfs2-mounter %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

install -Dpm 0755 nilfs2.sh %{buildroot}%{_bindir}/nilfs2.sh
install -d %{buildroot}/usr/share/applications
install -m 644 .applications/*.desktop %{buildroot}/usr/share/applications/


%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%post
setcap cap_sys_admin=ep /usr/bin/nilfs2-mounter

%files
/usr/share/applications/create-snapshot.desktop
/usr/share/applications/mount-snapshot.desktop
/usr/share/applications/unmount-snapshots.desktop
%{_bindir}/nilfs2.sh

%if %{without bootstrap}
%doc README.md
%{_bindir}/nilfs2-mounter
%endif

%gopkgfiles

%changelog
%autochangelog
